# -*- coding: utf-8 -*-
"""
Created on Sun May  1 18:34:57 2022

@author: Ronald Chitauro
"""



def Fabsequence(num):
    arrayNumbs = [1,1]
    
    if num ==1:
        return [1]
    
    if num == 2:
        return arrayNumbs
        
    if num > 2:
        i=0
        while (i<num-2):
            newNumb = arrayNumbs[i] + arrayNumbs[i+1]
            arrayNumbs.append(newNumb)
            i=i+1

            
    return arrayNumbs



numbers = input("How many numbers do you need to be generated by this sequence:")

print("The series is:", Fabsequence(int(numbers))) 



